services:
  smart-brain-api:
    container_name: backend
    # image: node:fermium-alpine3.12
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "3000:3000"
